### ISSUE TITLE
Issue installing node modules

### ISSUE THREAD

**Issue by Sulejman** [haadcode/orbit-db-cli#2]
After `npm install` I get following:

```
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout 866ffb0e81d3c4327a06e60ac75402f5b59242c7
npm ERR! fatal: reference is not a tree: 866ffb0e81d3c4327a06e60ac75402f5b59242c7
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sule/.npm/_logs/2017-09-12T22_03_08_577Z-debug.log
```

Here's a full log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i' ]
2 info using npm@5.4.1
3 info using node@v8.4.0
4 verbose npm-session 4427b22112837ad1
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall orbit-db-cli@0.0.3
7 info lifecycle orbit-db-cli@0.0.3~preinstall: orbit-db-cli@0.0.3
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly pacote git manifest for fs-ext@github:baudehlo/node-fs-ext#de78dda41f68c658cefc14897abbfeb5172e2fdf fetched in 355ms
14 info lifecycle ipfs-log@2.0.0~prepack: ipfs-log@2.0.0
15 info lifecycle ipfs-log@2.0.0~postpack: ipfs-log@2.0.0
16 silly pacote git manifest for ipfs-log@github:haadcode/ipfs-log#ff1df94cd1fd513198578efb1b7bb86096434157 fetched in 1612ms
17 silly pacote git manifest for level-js@github:timkuijsten/level.js#18e03adab34c49523be7d3d58fafb0c632f61303 fetched in 324ms
18 silly pacote git manifest for multiplex@github:dignifiedquire/multiplex#b5d5edd30454e2c978ee8c52df86f5f4840d2eab fetched in 323ms
19 silly fetchPackageMetaData error for orbit-db@github:orbitdb/orbit-db#866ffb0e81d3c4327a06e60ac75402f5b59242c7 Command failed: /usr/local/bin/git checkout 866ffb0e81d3c4327a06e60ac75402f5b59242c7
19 silly fetchPackageMetaData fatal: reference is not a tree: 866ffb0e81d3c4327a06e60ac75402f5b59242c7
20 verbose stack Error: Command failed: /usr/local/bin/git checkout 866ffb0e81d3c4327a06e60ac75402f5b59242c7
20 verbose stack fatal: reference is not a tree: 866ffb0e81d3c4327a06e60ac75402f5b59242c7
20 verbose stack
20 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
20 verbose stack     at emitTwo (events.js:125:13)
20 verbose stack     at ChildProcess.emit (events.js:213:7)
20 verbose stack     at maybeClose (internal/child_process.js:927:16)
20 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
21 verbose cwd /Users/sule/random_dir/orbit-db-cli
22 verbose Darwin 16.7.0
23 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
24 verbose node v8.4.0
25 verbose npm  v5.4.1
26 error code 128
27 error Command failed: /usr/local/bin/git checkout 866ffb0e81d3c4327a06e60ac75402f5b59242c7
27 error fatal: reference is not a tree: 866ffb0e81d3c4327a06e60ac75402f5b59242c7
28 verbose exit [ 1, true ]
```

**Comment by haadcode** [comment]
Hi @Sulejman and thanks for the bug report! Note that this module is currently still in development and may or may not work at any given time :)

I would recommend to check the current WIP branch at https://github.com/haadcode/orbit-db-cli/tree/feat/replication which contains the latest code and updated modules. I'm about to merge it to master very soon.

The error you're seeing here is due to npm not finding a specific branch/commit.

**Comment by haadcode** [comment]
This should now be fixed in master. Please re-open if the issue persists.

Thanks for reporting! :)
